### ISSUE TITLE
UserTiming not getting recorded

### ISSUE THREAD

**Issue by amit0rana** [theiconic/php-ga-measurement-protocol#12]
Hi,

 I am trying to record time for certain event using following code:

``` php
                  $analytics
                        ->setUserTiminCategory('transact')
                        ->setUserTimingVariableName('transactiontime')
                        ->setUserTimingTime(166)
                        ->setAsyncRequest(true)
                        ->sendTiming();
```

But this just doesn't reflect on GA panel. Any ideas why? I have validated hit and its alright

``` xml
{
  "hitParsingResult": [ {
    "valid": true,
    "parserMessage": [ ],
    "hit": "/debug/collect?v=1\u0026tid=UA-12345-1\u0026cid=123456789\u0026uid=1-11111\u0026dp=%2Ftransact\u0026t=timing\u0026utc=transact\u0026utv=transactiontime\u0026utt=1666"
  } ],
  "parserMessage": [ {
    "messageType": "INFO",
    "description": "Found 1 hit in the request."
  } ]
}
```

Other hits are getting recorded like page views, ecommerce etc

**Comment by amit0rana** [comment]
BTW setUserTiminCategory() has a typo. I am assuming its intentionally left like that.

**Comment by jorgeborges** [comment]
It should be a text value and the name of the param is utc, so everything looks OK in the code?
https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#utc

Are you still having this issue? I fixed the typo btw (old code with the typo should still work via a hack, the will be removed later in v3).
