### ISSUE TITLE
Issue with Symfony 3

### ISSUE THREAD

**Issue by irazasyed** [theiconic/php-ga-measurement-protocol#15]
Hi,

Refer: https://github.com/irazasyed/laravel-gamp/issues/10

This can be resolve if you update your composer to add support to 3.0:

```json
"symfony/finder": "^2.5|^3.0"
```

But I'm not sure what has been changed, So you'll need to check that and update it accordingly. If you don't, then people will not be able to use this with Laravel 5.2 which is the last stable version. 

Please do look into it and update.

**Comment by jorgeborges** [comment]
This got fixed in a2af5ecaf233a9d79e3af8619fe93c7e9b6682e1

I removed the dependency altogether! No need for Finder anymore.

Update to the latest version (should be automatic in your deployment pipeline if you used "^2.0" in Composer)

**Comment by irazasyed** [comment]
Thank you! 

Yes, I use `^2.0`.
