### ISSUE TITLE
IP Override

### ISSUE THREAD

**Issue by johnpaulmedina** [theiconic/php-ga-measurement-protocol#2]
When I send hits from the server it leaves active connections on the realtime part of GA.

Number 1 they are all from my server location
Number 2 I cant block out my IP because then it won't register the hits im sending
Number 3 Can I override the IP to be the users IP
Number 4 Is it possible to close the hit?

**Comment by jorgeborges** [comment]
@johnpaulmedina  There is an IP Override parameter. https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#uip

You can use it like:

```php
use TheIconic\Tracking\GoogleAnalytics\Analytics;

$analytics = new Analytics();

// Set required parameters: Protocol Version, Tracking ID, Client ID
// Then set IP Override like... 

$analytics->setIpOverride("202.126.106.175");
```

If you use an IDE like PHPStorm it should autocomplete.

Regarding the active connections on the realtime part of GA, everytime GA gets a hit (pageview, event, etc), I think it assumes the user stays around for a determined time (Session time), if it doesn't receive any hits from the same Client ID after a certain time, it closes the Session. You can edit the Session Time in the setting for the Property (Property > Tracking info > Session Settings).

**Comment by jorgeborges** [comment]
Just updated the README with this clarification. Does this answer your questions?

**Comment by johnpaulmedina** [comment]
Yes thanks for the prompt reply!
