### ISSUE TITLE
Cache Buster parameter should be sent as the final parameter in request

### ISSUE THREAD

**Issue by zhukovra** [theiconic/php-ga-measurement-protocol#21]
Prior to [Google Measurement Protocol documentation](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#z):

> Cache Buster
Used to send a random number in GET requests to ensure browsers and proxies don't cache hits. It should be sent as the final parameter of the request since we've seen some 3rd party internet filtering software add additional parameters to HTTP requests incorrectly.

**Comment by jorgeborges** [comment]
Should be an easy fix, I'll take care of it in the next release.
