### ISSUE TITLE
cURL Problem

### ISSUE THREAD

**Issue by grcasanova** [theiconic/php-ga-measurement-protocol#22]
Hello,
I am running this library on an Ubuntu VM and I keep getting this error:
cURL error 7: Failed to connect to ssl.google-analytics.com port 443: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

However, trying a _curl_ to that website works fine.

How to debug it?
Thank you

**Comment by jorgeborges** [comment]
Is this the same issue as http://stackoverflow.com/questions/37998791/curl-and-google-analytics ?

Sounds more like a configuration issue for the VM... Can you try connecting to other HTTPS API? Does it work?
