### ISSUE TITLE
What should  setClientId('12345678')

### ISSUE THREAD

**Issue by NobrainerWeb** [theiconic/php-ga-measurement-protocol#23]
We have a setup where only the conversion part is done via your PHP class / API.
Problem is all conversions are showing as (direct) / (none). 
Not realy sure where it goes wrong, but i'm thinking perhaps we need to send a clientId? 
What should setClientId() contain? now we just have ->setClientId('12345678') as per the demo.

**Comment by jorgeborges** [comment]
@NobrainerWeb  Can you be more specific? In what GA report are you viewing this? Some screenshots of the problem would help.

**Comment by NobrainerWeb** [comment]
@jorgeborges i have added a screenshot:
![skaermbillede 2016-07-28 kl 13 06 34](https://cloud.githubusercontent.com/assets/2331955/17210609/3239a1a6-54c4-11e6-8689-85b576697281.png) 

It's the Source/Medium column i'm talking about, before we fixed it, only direct / none was shown in this column. 
The initial tracking is done via JS and we only track the conversion via PHP. For analytics to tie the conversion to prior actions, it needs to know a clientID, saved in a cookie and read by GA JS.
Our fix was to parse the Cookie with PHP and pass the ClientID along with the conversion call.
Perhaps documentation should explain how to do this?

**Comment by jorgeborges** [comment]
@NobrainerWeb if you could contribute with documentation on how you did it that would be great! We can create a Wiki page and add a link in the README.

You can publish it in this issue and I'll copy it into a wiki page, I'll credit you for this of course.

**Comment by grzegorztomasiak** [comment]
@NobrainerWeb thanks for that info, I was just struggling with this issue today. I took '_ga' from $_COOKIE and pass it to the setClientId();

**Comment by jorgeborges** [comment]
OK, I put this in the README. Thanks for the heads up @NobrainerWeb

**Comment by grzegorztomasiak** [comment]
just to confirm,

in the previous post i was mistaken, passing _ga does not work, because it's not a client ID.
To make it work you have to $analytic->setClientId($idOrGuidOfYourUser);
and in your google analytic code ga('create', 'UA-XXXXXX-X', {clientId: idOrGuidOfYourUser});

and now it works :)
