### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' when deploying with rsync

### ISSUE THREAD

**Issue by matt-gnu** [theiconic/php-ga-measurement-protocol#28]
We deploy our web application with rsync to multiple backend servers. When we need to deploy updates to vendor/, we sometimes get:

`PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(/home/www/shop/vendor/theiconic/php-ga-measurement-protocol/src/Parameters/ContentInformation/.~tmp~): failed to open dir: Permission denied' in /home/www/shop/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:54
trace:
#0 /home/www/shop/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php(54): RecursiveDirectoryIterator->__construct('/home/www/shop/...', 4096)
#1 [internal function]: Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator->__construct('/home/www/shop/...', 4096)
#2 /home/www/shop/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php(90): RecursiveDirectoryIterator->getChildren()
#3 /home/www/shop/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php(79): Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator->getChildren()
#4 [internal function]: Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator->getChildren()
#5 [interna in /home/www/shop/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php on line 107`

Might I ask to enable http://api.symfony.com/2.3/Symfony/Component/Finder/Finder.html#method_ignoreUnreadableDirs on the finder instance in Analytics.php, Line 296? Or do you need to rely on AccessDeniedExceptions thrown?

thanks in advance!

**Comment by jorgeborges** [comment]
Update to the latest version, I got rid of the Symfony Finder dependency on version v2.2.0 released back in July 31.
