### ISSUE TITLE
Sku should be optional

### ISSUE THREAD

**Issue by DanielNoga** [theiconic/php-ga-measurement-protocol#32]
> sku is required for TheIconic\Tracking\GoogleAnalytics\Parameters\EnhancedEcommerce\Product
> TheIconic\Tracking\GoogleAnalytics\Exception\InvalidCompoundParameterException

Sku is optional not required according to Google documentation: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#pr_id

**Comment by jorgeborges** [comment]
boy, I could swear it was mandatory before! Its been over 2 years since I did it so I don't remember.

OK, this is an easy fix so I'll do it next week, or feel free to do the PR for it as well.

**Comment by rhrebecek** [comment]
Fixed in https://github.com/theiconic/php-ga-measurement-protocol/pull/33

**Comment by jorgeborges** [comment]
Thanks @rhrebecek
