### ISSUE TITLE
Curl connection refused

### ISSUE THREAD

**Issue by nicomollet** [theiconic/php-ga-measurement-protocol#34]
Hello,

I am using this lib with Yii2.

There are random errors connecting to www.google-analytics.com with Curl / Guzzle. Most of the time (99.9%), it works.

`[GuzzleHttp\Exception\ConnectException]
exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL
error 7: Failed to connect to www.google-analytics.com port 80:
Connection refused (see
http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in
/.../vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186`

Is there a way to prevent this?
Kind regards

**Comment by jorgeborges** [comment]
It could be something about your network, I would try to catch the exception and retry a second time.

**Comment by nicomollet** [comment]
Thank you, I managed to catch the exception.
