### ISSUE TITLE
[question] duplicate entry if used in combination with analytics.js

### ISSUE THREAD

**Issue by jacobdubail** [theiconic/php-ga-measurement-protocol#37]
Hi,

A number of clients use analytics.js to track e-commerce transactions. We want to add a layer of redundancy for cases where javascript is disabled or some other error occurs. We'll do this via a special transaction datafeed. What I can't figure out is whether or not a duplicate entry will be created in GA if both scripts fire (analytics.js and the measurement protocol).

Thanks for reading!

**Comment by jorgeborges** [comment]
They are considered different requests/hits to GA, so you will definitely get duplicates!

So you would have to detect on the server side if Javascript is off, and only then use this lib to send data to GA. This could be useful: http://stackoverflow.com/questions/121203/how-to-detect-if-javascript-is-disabled
