### ISSUE TITLE
Change `sendHit()` from `private` to `protected` method

### ISSUE THREAD

**Issue by khalwat** [theiconic/php-ga-measurement-protocol#38]
First of all, thanks again for your fantastic library.

I've found the need to subclass `use \TheIconic\Tracking\GoogleAnalytics\Analytics;`  so that I can do some additional business logic specific to my use-case, and also to extend the `sendHit()` method as a bottleneck to determine whether to send the analytics data or not.

There's one rub, however: because the method is declared as `private` I can't override it. I could fork the project, but I'd like to keep it in sync with the work you're doing.

So is there any chance you could change the `private` methods to `protected` to allow the type of thing?

**Comment by jorgeborges** [comment]
Done in latest release, you may run composer update @khalwat

**Comment by khalwat** [comment]
You are the best, thank you!
