### ISSUE TITLE
Improvement: cid should not be required when sending uid

### ISSUE THREAD

**Issue by tomcoonen** [theiconic/php-ga-measurement-protocol#39]
The Client ID should not be required when sending a User ID.
Reference code: https://github.com/theiconic/php-ga-measurement-protocol/blob/v2.4.1/src/Analytics.php#L606

**Comment by tomcoonen** [comment]
Possible fix: https://github.com/Hellocasa/php-ga-measurement-protocol/commit/05af3d28baef6b0362bbad70d89195cf2c862b07

**Comment by jorgeborges** [comment]
Fixed in the latest release, you may run composer update @tomcoonen
