### ISSUE TITLE
Google Analytics Reports Lots of Page Views From - "THE ICONIC GA Measurement Protocol PHP Client"

### ISSUE THREAD

**Issue by lukepolo** [theiconic/php-ga-measurement-protocol#4]
![screen shot 2015-03-17 at 12 47 34 pm](https://cloud.githubusercontent.com/assets/2066668/6692586/dd105e44-cca3-11e4-9d47-0c9cab9481b5.png)

Any idea why this happens?

**Comment by jorgeborges** [comment]
@lukepolo  That's the default **User-Agent** for the client. If you want to change it you could override it by setting your own user agent before sending the hit.

```$analytics->setUserAgentOverride('My Custom User-Agent');```

More info in: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#ua

**Comment by lukepolo** [comment]
Gotcha , also in my analytics view the real time the "user" never goes away , its stuck there . Any ideas on that ?

**Comment by lukepolo** [comment]
Found out it was pingdom
