### ISSUE TITLE
Pushing origin of the customer

### ISSUE THREAD

**Issue by enrico69** [theiconic/php-ga-measurement-protocol#42]
Hello

I easily managed to use this module inside Magento 2 to push orders information to Google Analytics.
However there is still a thing I don't know how to do: how to push the customer original location (the website he cames from).

I know how to get this information, but not how to use this module to push it to Google?

Regards

**Comment by jorgeborges** [comment]
If you meant the referral website, there is the Document Referrer parameter.

![screenshot 2017-04-23 09 49 45](https://cloud.githubusercontent.com/assets/1531431/25309213/547bd6c0-280a-11e7-891d-65d2171f9085.png)

As per documentation, you set it like this before sending the hit:

```php
$analytics->setDocumentReferrer('http://example.com/referrer.html');
```

**Comment by enrico69** [comment]
Thanks you. It seems to works perfectly.
