### ISSUE TITLE
how to use it without any framework ?!

### ISSUE THREAD

**Issue by matiazar** [theiconic/php-ga-measurement-protocol#43]
Hi. 
can anyone help me to use this component without any framework ?!

what file must I include?
what file must I use?

thanks in advance !

**Comment by jorgeborges** [comment]
Hi @matiazar 

You can install and use the library directly using Composer, a dependency manager for PHP. I suggest you do this tutorial on how to use Composer.
https://www.codementor.io/php/tutorial/composer-install-php-dependency-manager

Then come back and read the README, you will understand right away how to install it and use it in your project.

**Comment by matiazar** [comment]
Hi @jorgeborges  !
thanks for answering me.

I have already downloaded the package and installed/updated via composer.
Now I have all dependecies downloaded.
But I cannot know how to use it.

I have made this... but I have errors
Here is my code.. and my answer.

**** CODE ****
require_once (DIR_WS_VENDOR.'php-ga-measurement-protocol-master/src/Analytics.php');

use TheIconic\Tracking\GoogleAnalytics\Analytics;

echo "A ";
$analytics = new Analytics(true);
echo "B ";
$analytics
    ->setProtocolVersion('1')
    ->setTrackingId('UA-XXXXXX-1')
    ->setClientId('12345678')
    ->setDocumentPath('/mypage');
echo "C ";
// When you finish bulding the payload send a hit (such as an pageview or event)
$analytics->sendPageview();

print_r($analytics);

exit;

*** ANSWER ***

A B 
Fatal error: Class '\TheIconic\Tracking\GoogleAnalytics\Parameters\General\ProtocolVersion' not found in D:\Websites\testing\vendor\php-ga-measurement-protocol-master\src\Analytics.php on line 675


THANKS in advance !!!

**Comment by matiazar** [comment]
I have changed
require_once (DIR_WS_VENDOR.'php-ga-measurement-protocol-master/src/Analytics.php');
to
require_once (DIR_WS_VENDOR.'php-ga-measurement-protocol-master/vendor/autoload.php');

and now I think is working !

**Comment by matiazar** [comment]
Now I dont have any error.. but I cant see the "visit" in real time.

$analytics
    ->setProtocolVersion('1')
    ->setTrackingId('UA-xxxxxx-1')
    ->setClientId('1234567890')
    ->setDocumentPath('/prueba-ga2.html')
    ->setIpOverride("202.126.106.180");

// When you finish bulding the payload send a hit (such as an pageview or event)
$analytics->sendPageview();

I never see the /prueba-ga2.html on the real time overview

**Comment by acoleman-apc** [comment]
require_once ('./vendor/autoload.php');

This is probably what you actually need.
