### ISSUE TITLE
setDebug() not implemented?

### ISSUE THREAD

**Issue by vinnyusestrict** [theiconic/php-ga-measurement-protocol#46]
Trying to do `$analytics->setDebug(true)` raises the following exception:

```
Fatal error:  Uncaught exception 'BadMethodCallException' with message 'Method setDebug not defined for Analytics class' in /path/to/vendor/theiconic/php-ga-measurement-protocol/src/Analytics.php:518
Stack trace:
#0 /path/to/vendor/theiconic/php-ga-measurement-protocol/src/Analytics.php(431): TheIconic\Tracking\GoogleAnalytics\Analytics->getFullParameterClass('Debug', 'setDebug')
#1 /path/to/vendor/theiconic/php-ga-measurement-protocol/src/Analytics.php(539): TheIconic\Tracking\GoogleAnalytics\Analytics->setParameter('setDebug', Array)
#2 /path/to/tracker.php(77): TheIconic\Tracking\GoogleAnalytics\Analytics->__call('setDebug', Array)
#3 /path/to/tracker.php(77): TheIconic\Tracking\GoogleAnalytics\Analytics->setDebug(true)
#4 /path/to/tracker.php(47): SamcartGaTracker->__construct('UA-XXXXX-1')
#5 {main}
  thrown in <b>/path/to/vendor/theiconic/php-ga-measurement-protocol/src/Analytics.php</b> on line <b>518</b><br />
```

I'm trying to figure out why I only got a single hit in GA and it'd be great if the debug were working.

Thanks,
Vinny

**Comment by jorgeborges** [comment]
@vinnyusestrict Please make sure you are using at least v2.2.0, because there is a unit test for this method and it works fine. https://github.com/theiconic/php-ga-measurement-protocol/blob/master/tests/TheIconic/Tracking/GoogleAnalytics/AnalyticsTest.php#L256-L277

Run composer update and verify you at least have v2.2.0 in you composer.lock file.

**Comment by vinnyusestrict** [comment]
I'm using 1.x as I can't be sure what PHP version my clients will be using this with.

**Comment by jorgeborges** [comment]
That's the issue, unfortunately version 1.x stopped being maintained around 2 years ago.
