### ISSUE TITLE
Problem with custom metric

### ISSUE THREAD

**Issue by cimsict** [theiconic/php-ga-measurement-protocol#47]
Heey, 

I have a question about the custom metric usage of this api. 

My problem can be seen here: [https://stackoverflow.com/questions/44198809/google-analytics-custom-metrics-not-showing-up](url)

Am i doing something wrong? 

Thanks in advance!

**Comment by jorgeborges** [comment]
@cimsict I answered your question over at StackOverflow https://stackoverflow.com/questions/44198809/google-analytics-custom-metrics-not-showing-up/44345691#44345691
