### ISSUE TITLE
Installation without Composer

### ISSUE THREAD

**Issue by conorhub** [theiconic/php-ga-measurement-protocol#49]
For reasons I won't go into here, I'm attempting to use php-ga-measurement-protocol without Composer. I appreciate that it's the recommended route and I'm going off-piste here.

Using the following lines:
```
require("classes/theiconic_ga/Analytics.php");
require("classes/theiconic_ga/AnalyticsResponse.php");
require("classes/theiconic_ga/AnalyticsResponseInterface.php");
require("classes/theiconic_ga/NullAnalyticsResponse.php");
```

(with 'theiconic_ga' having the same files and structure as the project here) before using the first usage example code in your readme, I believed that any error that followed would help me track down any other requirements or lines I'd need to add. However, I'm stumped at the first hurdle when PHP has given me the following error:

`PHP Fatal error:  Uncaught Error: Class 'PHP Fatal error:  Interface 'TheIconic\Tracking\GoogleAnalytics\AnalyticsResponseInterface' not found in /classes/theiconic_ga/AnalyticsResponse.php on line 16`

**Comment by jorgeborges** [comment]
@conorhub Well, I haven't tried to do this, as I just use Composer.

My only advice would be to make sure you are requiring AnalyticsResponseInterface before AnalyticsResponse, because the former implements the latter. Switch those line in the code you posted.
