### ISSUE TITLE
Yii2 integration

### ISSUE THREAD

**Issue by baibaratsky** [theiconic/php-ga-measurement-protocol#5]
Hi, guys!
Thanks for a great tool.
I’ve just made an integration of your library with Yii2. Please list it in your README.
https://github.com/baibaratsky/yii2-ga-measurement-protocol

**Comment by jorgeborges** [comment]
Hi @baibaratsky,

Thanks for this, I have updated the README accordingly. I recommend you also get the word out there by posting in Yii 2 forums / community sites.

Cheers
