### ISSUE TITLE
How to test the version v1.2.0

### ISSUE THREAD

**Issue by leonmex** [theiconic/php-ga-measurement-protocol#53]
#Hello and sorry for make this Q but I'm working in the version in the version 1.2.0 and currently we can updated to the latest can you please give some way to test this version.

Best.

**Comment by jorgeborges** [comment]
Hi, sorry but can you please explain yourself better? What do you mean by test version 1.2.0? Maybe provide some examples of what you want to achieve.

**Comment by leonmex** [comment]
Hi @jorgeborges  thanks for your replay, and sorry for my previous question is solve.
