### ISSUE TITLE
How add custom parameter?

### ISSUE THREAD

**Issue by darkfriend** [theiconic/php-ga-measurement-protocol#54]
I add custom parameter `$analytics->setCustomDimension($arFields['cd1'],'dimension1')` and me output server error `When setting parameter TheIconic\Tracking\GoogleAnalytics\Parameters\CustomDimensionsMetrics\CustomDimension a numeric index between 1 - 200 must be passed for the second argument` 

How add my custom parameter 'dimension1' and set value for this parameter?

**Comment by darkfriend** [comment]
I understood) Thanks)

**Comment by FoxInFlame** [comment]
@darkfriend Care to write what you did? I'm confused on the same part.

**Comment by ktecho** [comment]
@darkfriend @FoxInFlame  Any of you found the way to do this?
