### ISSUE TITLE
Validating Hits

### ISSUE THREAD

**Issue by aronduby** [theiconic/php-ga-measurement-protocol#8]
Thanks for the great repo! Only thing that I would suggest is being able to do hit validation to help with debugging. 

https://developers.google.com/analytics/devguides/collection/protocol/v1/validating-hits

**Comment by jorgeborges** [comment]
I wasn't aware of this new feature! Thanks for pointing it out.

I'll check later how to implement it into the library.

**Comment by amit0rana** [comment]
You can try this https://github.com/amit0rana/php-ga-measurement-protocol/tree/validating_hits_debug_mode

Checkout Use Case section in Readme

**Comment by jorgeborges** [comment]
This feature was implemented in f9e8cef2ac89012bb9112a7130a9c0aa51a733e4

Update to the latest version (should be automatic in your deployment pipeline if you used "^2.0" in Composer)
