### ISSUE TITLE
Social interactions broken

### ISSUE THREAD

**Issue by flaviovs** [theiconic/php-ga-measurement-protocol#81]
The following call fails:

```php
$instance->setSocialAction('like');
```
Error is:

> Error: Call to undefined method TheIconic\Tracking\GoogleAnalytics\Parameters\SocialInteractions\SocialAction::setValue() in /app/vendor/theiconic/php-ga-measurement-protocol/src/Analytics.php:729

Same for `$instance->setSocialActionTarget('http://example.com');`.

Probable reason: classes in `src/Parameters/SocialInteractions/SocialAction*.php` don't inherit from `TheIconic\Tracking\GoogleAnalytics\Parameters\SingleParameter`.

**Comment by alberto-bottarini** [comment]
https://github.com/theiconic/php-ga-measurement-protocol/pull/84
https://github.com/theiconic/php-ga-measurement-protocol/pull/85

**Comment by jorgeborges** [comment]
Thanks for reporting @flaviovs, and thank you @alberto-bottarini for fixing.

I have released the patch version v2.7.2 with the fix.
