### ISSUE TITLE
Looking for Maintainers 

### ISSUE THREAD

**Issue by jorgeborges** [theiconic/php-ga-measurement-protocol#93]
Hi all,

As the title of the issue implies, I'm looking for maintainers for this library.

Ideally, someone that is using the library for their regular work, they would benefit from having it improve by releasing a new major version `v3` with PHP 7.1 or above support, fixing bugs, implementing new features and keeping up to date with improvements google makes to the measurement protocol.

This hasn't been my situation for many years, as THE ICONIC stopped using the library internally around 2015, however, I do see it has many millions of downloads, so I guess other companies are relying on it.

Any takers? If you have contributed to this library, please state your interest. I would make you a maintainer of the repo.

@stefanzweifel @alberto-bottarini @Nightbr @jfalcondb @edim24 @baibaratsky @irazasyed @venyii @ryo88c @rhrebecek @peterjaap @lombo @foaly-nr1 @amit0rana

**Comment by foaly-nr1** [comment]
FYI @Nightbr @roverwolf @kuraobi @ivan1986

**Comment by stefanzweifel** [comment]
Unfortunately I haven't actively used the package in the last few years. I'm probably not the best fit for the job.

But I would like to say my biggest thanks for developing and maintaining it for so long. Far too less we thank developers for building great packages. ❤️

**Comment by Preen** [comment]
I'm just about to start using this and thank you all for your hard work!
